echo "como manipular la base de datos desde dentro del contenedor"
echo "ingresemos docker exec -it db bash "
docker exec -it db bash
echo " comandos de manipulacion simbolo # es shell de linux"
echo "Sombolo >esta dentro de mongo "
echo "#mongo "
echo ">show dbs "
echo "use dbTienda"
echo "> show dbs " 
echo ""
echo "admin   0.000GB"
echo "config  0.000GB"
echo "local   0.000GB"
echo "> use dbtienda"
echo "switched to db dbtienda"
echo "> show dbs""
echo "admin   0.000GB"
echo "config  0.000GB"
echo "local   0.000GB"
echo "> show collections"
echo "> db.cliente.find()"
echo "> show collections"
echo "> db.cliente.insert({"nombre":"jose"})"
echo "WriteResult({ "nInserted" : 1 })"
echo "> show collections"
echo "cliente"
echo "> db.producto.find()"
echo "> db.producto.insert({"id":25},{"descripcion":"Azucar"})"
echo "WriteResult({ "nInserted" : 1 })"
echo "> show collections"
